// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TennisStringTracker.Api.Data;

#nullable disable

namespace TennisStringTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809100903_AddStringerBookmarks")]
    partial class AddStringerBookmarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TennisStringTracker.Api.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Author")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StringEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StringEntryId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityLabel")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrackerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackerId");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.StringEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfStringing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HorizontalWeight")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("Knotting")
                        .HasColumnType("integer");

                    b.Property<string>("StringModel")
                        .HasColumnType("text");

                    b.Property<Guid>("TrackerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VerticalWeight")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TrackerId");

                    b.ToTable("StringEntries");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.Stringer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Stringers");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.Tracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EditPasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trackers");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.TrackerBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StringerId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TrackerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackerId");

                    b.HasIndex("StringerId", "TrackerId")
                        .IsUnique();

                    b.ToTable("TrackerBookmarks");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.Comment", b =>
                {
                    b.HasOne("TennisStringTracker.Api.Models.StringEntry", "StringEntry")
                        .WithMany("Comments")
                        .HasForeignKey("StringEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StringEntry");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.HistoryEntry", b =>
                {
                    b.HasOne("TennisStringTracker.Api.Models.Tracker", "Tracker")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.StringEntry", b =>
                {
                    b.HasOne("TennisStringTracker.Api.Models.Tracker", "Tracker")
                        .WithMany("StringEntries")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.TrackerBookmark", b =>
                {
                    b.HasOne("TennisStringTracker.Api.Models.Stringer", "Stringer")
                        .WithMany("Bookmarks")
                        .HasForeignKey("StringerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisStringTracker.Api.Models.Tracker", "Tracker")
                        .WithMany()
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stringer");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.StringEntry", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.Stringer", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("TennisStringTracker.Api.Models.Tracker", b =>
                {
                    b.Navigation("HistoryEntries");

                    b.Navigation("StringEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
